#ifndef FUNK_H_INCLUDED
#define FUNK_H_INCLUDED
#include <iostream>
#include <string>
#include <iomanip>
#include <vector>
#include <fstream>
#include <algorithm>
#include <list>
#include <deque>
using std::cin;
using std::cout;
using std::endl;
using std::vector;
using std::string;
using std::setw;
using std::setprecision;
using std::stringstream;
using std::string;
using std::ifstream;
using std::swap;
using std::left;
using std::right;
using std::fixed;
using std::ofstream;
using std::list;
using std::deque;
void programa();
#endif // FUNK_H_INCLUDED
